name: Build Image

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf /usr/local/share/boost
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - uses: actions/checkout@v2

      - name: Make compressed workspace
        run: |
          sudo apt install -y btrfs-progs
          fallocate -l 64G workspace.img
          mkfs.btrfs workspace.img
          mkdir -p /home/runner/.cache/bazel
          sudo mount -o compress=zstd:15 workspace.img ~/.cache/bazel
          sudo chmod -R 777 /home/runner/.cache/bazel

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build base image
        run: bazel run :push_server_image
